namespace py LineThrift.square.enums

enum SquareMembershipState {
  JOIN_REQUESTED = 1
  JOINED = 2
  REJECTED = 3
  LEFT = 4
  KICK_OUT = 5
  BANNED = 6
  DELETED = 7
}

enum SquareMemberRole {
  ADMIN = 1
  CO_ADMIN = 2
  MEMBER = 10
}

enum SquareErrorCode {
  UNKNOWN = 0
  ILLEGAL_ARGUMENT = 400
  AUTHENTICATION_FAILURE = 401
  FORBIDDEN = 403
  NOT_FOUND = 404
  REVISION_MISMATCH = 409
  PRECONDITION_FAILED = 410
  INTERNAL_ERROR = 500
  NOT_IMPLEMENTED = 501
  TRY_AGAIN_LATER = 503
  MAINTENANCE = 505
}

enum PreconditionFailedExtraInfo {
  DUPLICATED_DISPLAY_NAME = 0
}

enum SquareType {
  CLOSED = 0
  OPEN = 1
}

enum SquareState {
  ALIVE = 0
  DELETED = 1
  SUSPENDED = 2
}

enum SquareChatType {
  OPEN = 1
  SECRET = 2
  ONE_ON_ONE = 3
  SQUARE_DEFAULT = 4
}

enum SquareChatState {
  ALIVE = 0
  DELETED = 1
  SUSPENDED = 2
}

enum MIDType {
  USER = 0
  ROOM = 1
  GROUP = 2
  SQUARE = 3
  SQUARE_CHAT = 4
  SQUARE_MEMBER = 5
  BOT = 6
}

enum ContentType {
  NONE = 0
  IMAGE = 1
  VIDEO = 2
  AUDIO = 3
  HTML = 4
  PDF = 5
  CALL = 6
  STICKER = 7
  PRESENCE = 8
  GIFT = 9
  GROUPBOARD = 10
  APPLINK = 11
  LINK = 12
  CONTACT = 13
  FILE = 14
  LOCATION = 15
  POSTNOTIFICATION = 16
  RICH = 17
  CHATEVENT = 18
  MUSIC = 19
  PAYMENT = 20
  EXTIMAGE = 21
}

enum MessageRelationType {
  FORWARD = 0
  AUTO_REPLY = 1
  SUBORDINATE = 2
}

enum ServiceCode {
  UNKNOWN = 0
  TALK = 1
  SQUARE = 2
}

enum SquareChatMembershipState {
  JOINED = 1
  LEFT = 2
}

enum SquareChatAnnouncementType {
  TEXT_MESSAGE = 0
}

enum SquareEventType {
  RECEIVE_MESSAGE = 0
  SEND_MESSAGE = 1
  NOTIFIED_JOIN_SQUARE_CHAT = 2
  NOTIFIED_INVITE_INTO_SQUARE_CHAT = 3
  NOTIFIED_LEAVE_SQUARE_CHAT = 4
  NOTIFIED_DESTROY_MESSAGE = 5
  NOTIFIED_MARK_AS_READ = 6
  NOTIFIED_UPDATE_SQUARE_MEMBER_PROFILE = 7
  NOTIFIED_KICKOUT_FROM_SQUARE = 19
  NOTIFIED_SHUTDOWN_SQUARE = 18
  NOTIFIED_DELETE_SQUARE_CHAT = 20
  NOTIFIED_UPDATE_SQUARE_CHAT_PROFILE_NAME = 30
  NOTIFIED_UPDATE_SQUARE_CHAT_PROFILE_IMAGE = 31
  NOTIFIED_UPDATE_SQUARE_CHAT_ANNOUNCEMENT = 37
  NOTIFIED_ADD_BOT = 33
  NOTIFIED_REMOVE_BOT = 34
  NOTIFIED_UPDATE_SQUARE = 8
  NOTIFIED_UPDATE_SQUARE_STATUS = 9
  NOTIFIED_UPDATE_SQUARE_AUTHORITY = 10
  NOTIFIED_UPDATE_SQUARE_MEMBER = 11
  NOTIFIED_UPDATE_SQUARE_CHAT = 12
  NOTIFIED_UPDATE_SQUARE_CHAT_STATUS = 13
  NOTIFIED_UPDATE_SQUARE_CHAT_MEMBER = 14
  NOTIFIED_CREATE_SQUARE_MEMBER = 15
  NOTIFIED_CREATE_SQUARE_CHAT_MEMBER = 16
  NOTIFIED_UPDATE_SQUARE_MEMBER_RELATION = 17
  NOTIFIED_UPDATE_SQUARE_FEATURE_SET = 32
  NOTIFIED_UPDATE_SQUARE_NOTE_STATUS = 36
  NOTIFICATION_JOIN_REQUEST = 21
  NOTIFICATION_JOINED = 22
  NOTIFICATION_PROMOTED_COADMIN = 23
  NOTIFICATION_PROMOTED_ADMIN = 24
  NOTIFICATION_DEMOTED_MEMBER = 25
  NOTIFICATION_KICKED_OUT = 26
  NOTIFICATION_SQUARE_DELETE = 27
  NOTIFICATION_SQUARE_CHAT_DELETE = 28
  NOTIFICATION_MESSAGE = 29
}

enum SquareMemberRelationState {
  NONE = 1
  BLOCKED = 2
}

enum SquareFeatureControlState {
  DISABLED = 1
  ENABLED = 2
}

enum BooleanState {
  NONE = 0
  OFF = 1
  ON = 2
}

enum SquareEventStatus {
  NORMAL = 1
  ALERT_DISABLED = 2
}

enum FetchDirection {
  FORWARD = 1
  BACKWARD = 2
}

enum ReportType {
  ADVERTISING = 1
  GENDER_HARASSMENT = 2
  HARASSMENT = 3
  OTHER = 4
}

enum SquareAttribute {
  NAME = 1
  WELCOME_MESSAGE = 2
  PROFILE_IMAGE = 3
  DESCRIPTION = 4
  SEARCHABLE = 6
  CATEGORY = 7
  INVITATION_URL = 8
  ABLE_TO_USE_INVITATION_URL = 9
  STATE = 10
}

enum SquareAuthorityAttribute {
  UPDATE_SQUARE_PROFILE = 1
  INVITE_NEW_MEMBER = 2
  APPROVE_JOIN_REQUEST = 3
  CREATE_POST = 4
  CREATE_OPEN_SQUARE_CHAT = 5
  DELETE_SQUARE_CHAT_OR_POST = 6
  REMOVE_SQUARE_MEMBER = 7
  GRANT_ROLE = 8
  ENABLE_INVITATION_TICKET = 9
  CREATE_CHAT_ANNOUNCEMENT = 10
}

enum SquareChatAttribute {
  NAME = 2
  SQUARE_CHAT_IMAGE = 3
  STATE = 4
}

enum SquareChatMemberAttribute {
  MEMBERSHIP_STATE = 4
  NOTIFICATION_MESSAGE = 6
}

enum SquareFeatureSetAttribute {
  CREATING_SECRET_SQUARE_CHAT = 1
  INVITING_INTO_OPEN_SQUARE_CHAT = 2
}

enum SquareMemberAttribute {
  DISPLAY_NAME = 1
  PROFILE_IMAGE = 2
  ABLE_TO_RECEIVE_MESSAGE = 3
  MEMBERSHIP_STATE = 5
  ROLE = 6
  PREFERENCE = 7
}

enum SquarePreferenceAttribute {
  FAVORITE = 1
  NOTI_FOR_NEW_JOIN_REQUEST = 2
}

enum SquareMemberRelationAttribute {
  BLOCKED = 1
}

