namespace py LineThrift.talk.enums
namespace go LineThrift.talk.enums

enum CallFlowType {
  NEW = 1;
  PLANET = 2;
}

enum FeatureType {
  OBS_VIDEO = 1
  OBS_GENERAL = 2
}

enum ChatRoomAnnouncementType {
  MESSAGE = 0
  NOTE = 1
  CHANNEL = 2
}

enum FriendRequestDirection {
  INCOMING = 1
  OUTGOING = 2
}

enum FriendRequestMethod {
  TIMELINE = 1
  NEARBY = 2
  SQUARE = 3
}

enum NotificationType {
  APPLE_APNS = 1
  GOOGLE_C2DM = 2
  NHN_NNI = 3
  SKT_AOM = 4
  MS_MPNS = 5
  RIM_BIS = 6
  GOOGLE_GCM = 7
  NOKIA_NNAPI = 8
  TIZEN = 9
  LINE_BOT = 17
  LINE_WAP = 18
  APPLE_APNS_VOIP = 19
  MS_WNS = 20
  GOOGLE_FCM = 21
  CLOVA = 22
  CLOVA_VOIP = 23
}

enum EmailConfirmationStatus {
  NOT_SPECIFIED = 0
  NOT_YET = 1
  DONE = 3
  NEED_ENFORCED_INPUT = 4
}

enum AccountMigrationPincodeType {
  NOT_APPLICABLE = 0
  NOT_SET = 1
  SET = 2
  NEED_ENFORCED_INPUT = 3
}

enum SecurityCenterSettingsType {
  NOT_APPLICABLE = 0
  NOT_SET = 1
  SET = 2
  NEED_ENFORCED_INPUT = 3
}

enum CustomMode {
  PROMOTION_FRIENDS_INVITE = 1
  CAPABILITY_SERVER_SIDE_SMS = 2
  LINE_CLIENT_ANALYTICS_CONFIGURATION = 3
}

enum SettingsAttribute2 {
  NOTIFICATION_ENABLE = 0
  NOTIFICATION_MUTE_EXPIRATION = 1
  NOTIFICATION_NEW_MESSAGE = 2
  NOTIFICATION_GROUP_INVITATION = 3
  NOTIFICATION_SHOW_MESSAGE = 4
  NOTIFICATION_INCOMING_CALL = 5
  NOTIFICATION_SOUND_MESSAGE = 8
  NOTIFICATION_SOUND_GROUP = 9
  NOTIFICATION_DISABLED_WITH_SUB = 16
  NOTIFICATION_PAYMENT = 17
  NOTIFICATION_MENTION = 40
  NOTIFICATION_THUMBNAIL = 45
  PRIVACY_SYNC_CONTACTS = 6
  PRIVACY_SEARCH_BY_PHONE_NUMBER = 7
  PRIVACY_SEARCH_BY_USERID = 13
  PRIVACY_SEARCH_BY_EMAIL = 14
  PRIVACY_ALLOW_SECONDARY_DEVICE_LOGIN = 21
  PRIVACY_PROFILE_IMAGE_POST_TO_MYHOME = 23
  PRIVACY_PROFILE_MUSIC_POST_TO_MYHOME = 35
  PRIVACY_ALLOW_FRIEND_REQUEST = 30
  PRIVACY_RECV_MESSAGES_FROM_NOT_FRIEND = 25
  PRIVACY_AGREE_USE_LINECOIN_TO_PAIDCALL = 26
  PRIVACY_AGREE_USE_PAIDCALL = 27
  CONTACT_MY_TICKET = 10
  IDENTITY_PROVIDER = 11
  IDENTITY_IDENTIFIER = 12
  SNS_ACCOUNT = 19
  PHONE_REGISTRATION = 20
  PREFERENCE_LOCALE = 15
  CUSTOM_MODE = 22
  EMAIL_CONFIRMATION_STATUS = 24
  ACCOUNT_MIGRATION_PINCODE = 28
  ENFORCED_INPUT_ACCOUNT_MIGRATION_PINCODE = 29
  SECURITY_CENTER_SETTINGS = 18
  E2EE_ENABLE = 33
  HITOKOTO_BACKUP_REQUESTED = 34
  CONTACT_ALLOW_FOLLOWING = 36
  PRIVACY_ALLOW_NEARBY = 37
  AGREEMENT_NEARBY = 38
  AGREEMENT_SQUARE = 39
  ALLOW_UNREGISTRATION_SECONDARY_DEVICE = 41
  AGREEMENT_BOT_USE = 42
  AGREEMENT_SHAKE_FUNCTION = 43
  AGREEMENT_MOBILE_CONTACT_NAME = 44
  AGREEMENT_SOUND_TO_TEXT = 46
  AGREEMENT_PRIVACY_POLICY_VERSION = 47
  AGREEMENT_AD_BY_WEB_ACCESS = 48
  AGREEMENT_PHONE_NUMBER_MATCHING = 49
  AGREEMENT_COMMUNICATION_INFO = 50
}

enum WapInvitationType {
  REGISTRATION = 1
  CHAT = 2
}

enum SyncCategory {
  PROFILE = 0
  SETTINGS = 1
  OPS = 2
  CONTACT = 3
  RECOMMEND = 4
  BLOCK = 5
  GROUP = 6
  ROOM = 7
  NOTIFICATION = 8
  ADDRESS_BOOK = 9
}

enum ReportCategory {
  PUSH_NORMAL_PLAIN = 0
  PUSH_NORMAL_E2EE = 1
  PUSH_VOIP_PLAIN = 2
  PUSH_VOIP_E2EE = 3
}

enum SyncActionType {
  SYNC = 0
  REPORT = 1
}

enum SpammerReason {
  OTHER = 0
  ADVERTISING = 1
  GENDER_HARASSMENT = 2
  HARASSMENT = 3
}

enum EmailConfirmationType {
  SERVER_SIDE_EMAIL = 0
  CLIENT_SIDE_EMAIL = 1
}

enum CommitMessageResultCode {
  DELIVERED = 0
  DELIVERY_SKIPPED = 1
  DELIVERY_RESTRICTED = 2
}

enum ModificationType {
  ADD = 0
  REMOVE = 1
  MODIFY = 2
}

enum ContactSetting {
  CONTACT_SETTING_NOTIFICATION_DISABLE = 1
  CONTACT_SETTING_DISPLAY_NAME_OVERRIDE = 2
  CONTACT_SETTING_CONTACT_HIDE = 4
  CONTACT_SETTING_FAVORITE = 8
  CONTACT_SETTING_DELETE = 16
}

enum GroupPreferenceAttribute {
  INVITATION_TICKET = 1
  FAVORITE_TIMESTAMP = 2
}

enum SettingsAttribute {
  ALL = 2147483647
  NOTIFICATION_ENABLE = 1
  NOTIFICATION_MUTE_EXPIRATION = 2
  NOTIFICATION_NEW_MESSAGE = 4
  NOTIFICATION_GROUP_INVITATION = 8
  NOTIFICATION_SHOW_MESSAGE = 16
  NOTIFICATION_INCOMING_CALL = 32
  NOTIFICATION_SOUND_MESSAGE = 256
  NOTIFICATION_SOUND_GROUP = 512
  NOTIFICATION_DISABLED_WITH_SUB = 65536
  NOTIFICATION_PAYMENT = 131072
  PRIVACY_SYNC_CONTACTS = 64
  PRIVACY_SEARCH_BY_PHONE_NUMBER = 128
  PRIVACY_SEARCH_BY_USERID = 8192
  PRIVACY_SEARCH_BY_EMAIL = 16384
  PRIVACY_ALLOW_SECONDARY_DEVICE_LOGIN = 2097152
  PRIVACY_PROFILE_IMAGE_POST_TO_MYHOME = 8388608
  PRIVACY_ALLOW_FRIEND_REQUEST = 1073741824
  PRIVACY_RECV_MESSAGES_FROM_NOT_FRIEND = 33554432
  PRIVACY_AGREE_USE_LINECOIN_TO_PAIDCALL = 67108864
  PRIVACY_AGREE_USE_PAIDCALL = 134217728
  CONTACT_MY_TICKET = 1024
  IDENTITY_PROVIDER = 2048
  IDENTITY_IDENTIFIER = 4096
  SNS_ACCOUNT = 524288
  PHONE_REGISTRATION = 1048576
  PREFERENCE_LOCALE = 32768
  CUSTOM_MODE = 4194304
  EMAIL_CONFIRMATION_STATUS = 16777216
  ACCOUNT_MIGRATION_PINCODE = 268435456
  ENFORCED_INPUT_ACCOUNT_MIGRATION_PINCODE = 536870912
  SECURITY_CENTER_SETTINGS = 262144
}

enum VerificationResult {
  FAILED = 0
  OK_NOT_REGISTERED_YET = 1
  OK_REGISTERED_WITH_SAME_DEVICE = 2
  OK_REGISTERED_WITH_ANOTHER_DEVICE = 3
}

